version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:80"
    environment:
      - NAME=Server
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge